### ISSUE TITLE
Quick Question RE Title Page fonts

### ISSUE THREAD

**Issue by rjbprime** [Vladar4/DND-5e-LaTeX-Template-Module-Example#1]
Hi @Vladar4: How do I change the title page font, to resemble the Chapter Heading fonts, but bigger? I'm trying to re-create my homebrew, that was previously hosted on Homebrewery, but as I'm more familiar with HTML, not LaTeX, (complete noob to LaTeX, as in, I'm doing this as a crash course...)

Loving using LaTeX, but some parts are confusing... Hence the question. Is there a way you can show an example? I'm using your title page code, with the recent DND-5e-LaTeX-Template, version 0.6.0, and I've gotten most of it worked out, but the title page font is doing my head in.

Please help.

Kind Regards,

RJBPrime

**Comment by Vladar4** [comment]
You might want to check out [LaTeX/Fonts](https://en.wikibooks.org/wiki/LaTeX/Fonts#Available_LaTeX_Fonts) wiki page for that, plus see font declarations of [DND-5e-LaTeX-Template](https://github.com/evanbergeron/DND-5e-LaTeX-Template/blob/master/lib/dndfonts.sty) for reference.
